services:
  front-end:
    image: consumer:0.1
    depends_on:
      - Tp_Composants
    ports:
      - "8081:8081"
  Tp_Composants:
    image: my-ms:0.1
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      DB_URL: mongodb://mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: meme_service_db
    volumes:
      - db:/data/db/

volumes:
  db: